# Generated by Django 5.1.1 on 2024-10-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
