# Generated by Django 5.1.4 on 2024-12-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
    ]
