# Generated by Django 5.1.4 on 2024-12-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_event_floor_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booth',
            name='reserved_by',
        ),
        migrations.AlterField(
            model_name='booth',
            name='booth_type',
            field=models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard')], default='standard', max_length=20),
        ),
    ]
