# Generated by Django 5.1.4 on 2025-01-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_exhibitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='floor_plan',
            new_name='floor_plan_premium',
        ),
        migrations.AddField(
            model_name='event',
            name='floor_plan_standard',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
    ]
