# Generated by Django 5.1.4 on 2025-01-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_rename_floor_plan_event_floor_plan_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='premium_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='standard_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
