# Generated by Django 5.1.4 on 2025-01-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_remove_booth_price_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
