# Generated by Django 5.1.4 on 2025-01-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_order_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
