# Generated by Django 5.1.4 on 2025-01-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_remove_order_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order_number',
        ),
    ]
