# Generated by Django 5.1.4 on 2025-01-15 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_order_unique_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='booth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='reservations.booth'),
        ),
    ]
