# Generated by Django 5.1.4 on 2025-01-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_alter_orderitem_booth'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exhibitor',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='company',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='event',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Exhibitor',
        ),
    ]
