# Generated by Django 5.1.4 on 2025-01-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_alter_exhibitor_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='premium_features',
            field=models.TextField(blank=True, help_text="Enter premium features, separated by commas (e.g., 'WiFi, VIP Table, Premium Chairs')", null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='standard_features',
            field=models.TextField(blank=True, help_text="Enter standard features, separated by commas (e.g., 'WiFi, Table, Chairs')", null=True),
        ),
    ]
